### ISSUE TITLE
DEPLOY_HOSTNAME and organization

### ISSUE THREAD

**Issue by aboire** [jehartzog/galaxy-autoscale#3]
DEPLOY_HOSTNAME (eu-west-1.galaxy.meteor.com) is not configurable, and this is not intended for an organization (--owner)

**Comment by jehartzog** [comment]
Is this console output from when you are trying to deploy your app? If so, it looks like you still working out how to upload your app to Galaxy, which this package doesn't really affect.

This package uses your Galaxy username and password to login in a headless browser, so it doesn't affect or require your local console to be logged in to a Galaxy account.

**Comment by aboire** [comment]
I identify myself on galaxy on this url https://eu-west-1.galaxy.meteor.com
and the url of the app is https://eu-west-1.galaxy.meteor.com/app/www.example.com

https://github.com/jehartzog/galaxy-autoscale/blob/c77b9ba3bb377e9153d8a152d64ab1d6352a9b08/lib/autoscale.js#L24

**Comment by jehartzog** [comment]
Ah I see! I'll issue a change to allow setting the entire URL instead of assuming the default us-east-1. Thanks for letting me know.

**Comment by jehartzog** [comment]
I've pushed [v2.1.0](https://github.com/jehartzog/galaxy-autoscale/releases/tag/v2.1.0) which fixes this, closing the issue.
